"use strict";
exports.__esModule = true;
var Carro_1 = require("./Carro");
var c1;
c1 = new Carro_1.Carro();
c1.setAno(2001);
c1.setModelo("Palio Adventure");
c1.setPlaca("FAG2469");
c1.setCor("Branca");
c1.ligar();
